#!/usr/bin/env python

import sys

del sys.path[0:10]
sys.path.append('/data/data/ussr.razar.youtube_dl/files/plat-linux')
sys.path.append('/data/data/ussr.razar.youtube_dl/files/lib-dynload')
sys.path.append('/sdcard/python3.5.zip')

import youtube_dl

if __name__ == '__main__':
    youtube_dl.main()
